#!/usr/bin/env bash
# Creates nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
