#!/usr/bin/env bash
#install configure HaProxy

sudo apt update
sudo apt-get  -y install haproxy

printf %s "
frontend haproxy
    bind *:80
    mode http
    default_backend  cuore
backend cuore
    balance roundrobin
        server 1563-web-01 35.231.228.4:80 check
        server 1563-web-02 35.196.160.52:80 check
"        >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
