#!/usr/bin/env bash
#install configure HaProxy

sudo apt update
sudo apt-get  -y install haproxy

printf %s "
frontend haproxy
    bind *:80
    mode http
    default_backend  toto
backend toto
    balance roundrobin
        server 1407-web-01 34.74.203.142:80 check
        server 1407-web-02 34.73.40.242:80 check
"        >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
