#!/usr/bin/env bash
# This script is displaying numbers from 1 to 100
i=1
until [ $i -eq 101 ]
		do
			if [ $((i % 3)) == 0 -a $((i % 5)) == 0 ] 
			then
					echo "FizzBuzz"
			elif [ $((i % 3)) == 0 ]
			then
					echo "Fizz"
			elif [ $((i % 5)) == 0 ]
			then
					echo "Buzz"
			else
					echo "$i"
			fi
			i=$(( i+1 ))
		done